### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by xiaofsu** [lttztt/B85-i5_4590-HACKINTOSH-Clover-EFI#1]
我电脑是：
CPU：i5-4590
显卡：核显
主板：[华擎B85](http://www.asrockchina.com.cn/mb/Intel/Fatal1ty%20B85%20Killer/index.cn.asp)

问一下是否能用这个EFI

**Comment by lttztt** [comment]
主板没问题，我这个是免驱独显，不太确定有没有问题。

**Comment by xiaofsu** [comment]
OK，那我就先试试...我第一次装黑苹果，小白2333

**Comment by lttztt** [comment]
我也是小白，这是为了记录一下。 嘻嘻

**Comment by lttztt** [comment]
推荐你先使用黑果小兵里的安装成功，然后在替换符合机型的EFI做适配，一点一点来。

**Comment by xiaofsu** [comment]
😂😂你有没有什么安装教程啥的？我准备看B站来自己安装...但是毫无底气啊...
